// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationFormApi.Persistence;

#nullable disable

namespace RegistrationFormApi.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241114131653_AddAddressTrigger")]
    partial class AddAddressTrigger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistrationFormApi.Domain.Entities.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressID"));

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("int");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<int>("FlatNumber")
                        .HasColumnType("int");

                    b.Property<int>("GovernateID")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AddressID");

                    b.HasIndex("CityID");

                    b.HasIndex("GovernateID");

                    b.HasIndex("UserID");

                    b.ToTable("Addresses", t =>
                        {
                            t.HasTrigger("trg_UpdateGovernateUserCount");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RegistrationFormApi.Domain.Entities.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovernateID")
                        .HasColumnType("int");

                    b.HasKey("CityID");

                    b.HasIndex("GovernateID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = 1,
                            CityName = "Abbasiya",
                            GovernateID = 1
                        },
                        new
                        {
                            CityID = 2,
                            CityName = "New Cairo",
                            GovernateID = 1
                        },
                        new
                        {
                            CityID = 3,
                            CityName = "Heliopolis",
                            GovernateID = 1
                        },
                        new
                        {
                            CityID = 4,
                            CityName = "Nasr City",
                            GovernateID = 1
                        },
                        new
                        {
                            CityID = 5,
                            CityName = "Alexandria",
                            GovernateID = 2
                        },
                        new
                        {
                            CityID = 6,
                            CityName = "Sidi Bishr",
                            GovernateID = 2
                        },
                        new
                        {
                            CityID = 7,
                            CityName = "El Montaza",
                            GovernateID = 2
                        },
                        new
                        {
                            CityID = 8,
                            CityName = "6th of October",
                            GovernateID = 3
                        },
                        new
                        {
                            CityID = 9,
                            CityName = "Badrashin",
                            GovernateID = 3
                        },
                        new
                        {
                            CityID = 10,
                            CityName = "Kerdasa",
                            GovernateID = 3
                        },
                        new
                        {
                            CityID = 11,
                            CityName = "Benha",
                            GovernateID = 4
                        },
                        new
                        {
                            CityID = 12,
                            CityName = "Shibin El Kom",
                            GovernateID = 4
                        },
                        new
                        {
                            CityID = 13,
                            CityName = "Mansoura",
                            GovernateID = 5
                        },
                        new
                        {
                            CityID = 14,
                            CityName = "Talkha",
                            GovernateID = 5
                        },
                        new
                        {
                            CityID = 15,
                            CityName = "Dikirnis",
                            GovernateID = 5
                        },
                        new
                        {
                            CityID = 16,
                            CityName = "Zagazig",
                            GovernateID = 6
                        },
                        new
                        {
                            CityID = 17,
                            CityName = "Mashtool El Souq",
                            GovernateID = 6
                        },
                        new
                        {
                            CityID = 18,
                            CityName = "Kafr El Sheikh",
                            GovernateID = 7
                        },
                        new
                        {
                            CityID = 19,
                            CityName = "Desouk",
                            GovernateID = 7
                        },
                        new
                        {
                            CityID = 20,
                            CityName = "Damanhur",
                            GovernateID = 8
                        },
                        new
                        {
                            CityID = 21,
                            CityName = "Kafr El Dawar",
                            GovernateID = 8
                        },
                        new
                        {
                            CityID = 22,
                            CityName = "Shibin El Kom",
                            GovernateID = 9
                        },
                        new
                        {
                            CityID = 23,
                            CityName = "Minuf",
                            GovernateID = 9
                        },
                        new
                        {
                            CityID = 24,
                            CityName = "Tanta",
                            GovernateID = 10
                        },
                        new
                        {
                            CityID = 25,
                            CityName = "El Mahalla El Kubra",
                            GovernateID = 10
                        },
                        new
                        {
                            CityID = 26,
                            CityName = "Beni Suef",
                            GovernateID = 11
                        },
                        new
                        {
                            CityID = 27,
                            CityName = "Ehnasia",
                            GovernateID = 11
                        },
                        new
                        {
                            CityID = 28,
                            CityName = "Faiyum",
                            GovernateID = 12
                        },
                        new
                        {
                            CityID = 29,
                            CityName = "Ibshaway",
                            GovernateID = 12
                        },
                        new
                        {
                            CityID = 30,
                            CityName = "Minya",
                            GovernateID = 13
                        },
                        new
                        {
                            CityID = 31,
                            CityName = "Abu Qurqas",
                            GovernateID = 13
                        },
                        new
                        {
                            CityID = 32,
                            CityName = "Asyut",
                            GovernateID = 14
                        },
                        new
                        {
                            CityID = 33,
                            CityName = "Sahel Selim",
                            GovernateID = 14
                        },
                        new
                        {
                            CityID = 34,
                            CityName = "Sohag",
                            GovernateID = 15
                        },
                        new
                        {
                            CityID = 35,
                            CityName = "Gerga",
                            GovernateID = 15
                        },
                        new
                        {
                            CityID = 36,
                            CityName = "Qena",
                            GovernateID = 16
                        },
                        new
                        {
                            CityID = 37,
                            CityName = "Nag Hammadi",
                            GovernateID = 16
                        },
                        new
                        {
                            CityID = 38,
                            CityName = "Luxor",
                            GovernateID = 17
                        },
                        new
                        {
                            CityID = 39,
                            CityName = "Esna",
                            GovernateID = 17
                        },
                        new
                        {
                            CityID = 40,
                            CityName = "Aswan",
                            GovernateID = 18
                        },
                        new
                        {
                            CityID = 41,
                            CityName = "Kom Ombo",
                            GovernateID = 18
                        },
                        new
                        {
                            CityID = 42,
                            CityName = "Hurghada",
                            GovernateID = 19
                        },
                        new
                        {
                            CityID = 43,
                            CityName = "Safaga",
                            GovernateID = 19
                        },
                        new
                        {
                            CityID = 44,
                            CityName = "El Arish",
                            GovernateID = 20
                        },
                        new
                        {
                            CityID = 45,
                            CityName = "Sheikh Zuweid",
                            GovernateID = 20
                        },
                        new
                        {
                            CityID = 46,
                            CityName = "Sharm El Sheikh",
                            GovernateID = 21
                        },
                        new
                        {
                            CityID = 47,
                            CityName = "Dahab",
                            GovernateID = 21
                        },
                        new
                        {
                            CityID = 48,
                            CityName = "Matruh",
                            GovernateID = 22
                        },
                        new
                        {
                            CityID = 49,
                            CityName = "Sidi Abdel Rahman",
                            GovernateID = 22
                        },
                        new
                        {
                            CityID = 50,
                            CityName = "Kharga",
                            GovernateID = 23
                        },
                        new
                        {
                            CityID = 51,
                            CityName = "Dakhla",
                            GovernateID = 23
                        },
                        new
                        {
                            CityID = 52,
                            CityName = "Port Said",
                            GovernateID = 24
                        },
                        new
                        {
                            CityID = 53,
                            CityName = "Suez",
                            GovernateID = 25
                        });
                });

            modelBuilder.Entity("RegistrationFormApi.Domain.Entities.Governate", b =>
                {
                    b.Property<int>("GovernateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GovernateID"));

                    b.Property<string>("GovernateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GovernateID");

                    b.ToTable("Governates");

                    b.HasData(
                        new
                        {
                            GovernateID = 1,
                            GovernateName = "Cairo"
                        },
                        new
                        {
                            GovernateID = 2,
                            GovernateName = "Alexandria"
                        },
                        new
                        {
                            GovernateID = 3,
                            GovernateName = "Giza"
                        },
                        new
                        {
                            GovernateID = 4,
                            GovernateName = "Qalyubia"
                        },
                        new
                        {
                            GovernateID = 5,
                            GovernateName = "Dakahlia"
                        },
                        new
                        {
                            GovernateID = 6,
                            GovernateName = "Sharqia"
                        },
                        new
                        {
                            GovernateID = 7,
                            GovernateName = "Kafr El Sheikh"
                        },
                        new
                        {
                            GovernateID = 8,
                            GovernateName = "Beheira"
                        },
                        new
                        {
                            GovernateID = 9,
                            GovernateName = "Minufiya"
                        },
                        new
                        {
                            GovernateID = 10,
                            GovernateName = "Gharbia"
                        },
                        new
                        {
                            GovernateID = 11,
                            GovernateName = "Beni Suef"
                        },
                        new
                        {
                            GovernateID = 12,
                            GovernateName = "Faiyum"
                        },
                        new
                        {
                            GovernateID = 13,
                            GovernateName = "Menya"
                        },
                        new
                        {
                            GovernateID = 14,
                            GovernateName = "Asyut"
                        },
                        new
                        {
                            GovernateID = 15,
                            GovernateName = "Sohag"
                        },
                        new
                        {
                            GovernateID = 16,
                            GovernateName = "Qena"
                        },
                        new
                        {
                            GovernateID = 17,
                            GovernateName = "Luxor"
                        },
                        new
                        {
                            GovernateID = 18,
                            GovernateName = "Aswan"
                        },
                        new
                        {
                            GovernateID = 19,
                            GovernateName = "Red Sea"
                        },
                        new
                        {
                            GovernateID = 20,
                            GovernateName = "North Sinai"
                        },
                        new
                        {
                            GovernateID = 21,
                            GovernateName = "South Sinai"
                        },
                        new
                        {
                            GovernateID = 22,
                            GovernateName = "Matruh"
                        },
                        new
                        {
                            GovernateID = 23,
                            GovernateName = "New Valley"
                        },
                        new
                        {
                            GovernateID = 24,
                            GovernateName = "Port Said"
                        },
                        new
                        {
                            GovernateID = 25,
                            GovernateName = "Suez"
                        });
                });

            modelBuilder.Entity("RegistrationFormApi.Domain.Entities.GovernateUserCount", b =>
                {
                    b.Property<int>("GovernateID")
                        .HasColumnType("int");

                    b.Property<int>("UserCount")
                        .HasColumnType("int");

                    b.HasKey("GovernateID");

                    b.ToTable("GovernateUserCounts");
                });

            modelBuilder.Entity("RegistrationFormApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RegistrationFormApi.Domain.Entities.Address", b =>
                {
                    b.HasOne("RegistrationFormApi.Domain.Entities.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistrationFormApi.Domain.Entities.Governate", "Governate")
                        .WithMany("Addresses")
                        .HasForeignKey("GovernateID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistrationFormApi.Domain.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Governate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RegistrationFormApi.Domain.Entities.City", b =>
                {
                    b.HasOne("RegistrationFormApi.Domain.Entities.Governate", "Governate")
                        .WithMany("Cities")
                        .HasForeignKey("GovernateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governate");
                });

            modelBuilder.Entity("RegistrationFormApi.Domain.Entities.GovernateUserCount", b =>
                {
                    b.HasOne("RegistrationFormApi.Domain.Entities.Governate", "Governate")
                        .WithOne("GovernateUserCount")
                        .HasForeignKey("RegistrationFormApi.Domain.Entities.GovernateUserCount", "GovernateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governate");
                });

            modelBuilder.Entity("RegistrationFormApi.Domain.Entities.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("RegistrationFormApi.Domain.Entities.Governate", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cities");

                    b.Navigation("GovernateUserCount")
                        .IsRequired();
                });

            modelBuilder.Entity("RegistrationFormApi.Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
